// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_S91nTYAWqO5gmPZbSg4lKLCj_Uv2ezc',
    appId: '1:538784837581:web:5ed5b4b3c8fa5e5e9f1e84',
    messagingSenderId: '538784837581',
    projectId: 'capstone-53c84',
    authDomain: 'capstone-53c84.firebaseapp.com',
    databaseURL: 'https://capstone-53c84-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-53c84.appspot.com',
    measurementId: 'G-Z3M46DRKRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO3a__olfiwXxT_oMDX3BhwGkvmIfl1zw',
    appId: '1:538784837581:android:949f7b8df9b58f299f1e84',
    messagingSenderId: '538784837581',
    projectId: 'capstone-53c84',
    databaseURL: 'https://capstone-53c84-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-53c84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU1RWV7w3P_TkT5nBcmk-gI4LeUKSS9mw',
    appId: '1:538784837581:ios:65c743532284b4e19f1e84',
    messagingSenderId: '538784837581',
    projectId: 'capstone-53c84',
    databaseURL: 'https://capstone-53c84-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-53c84.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU1RWV7w3P_TkT5nBcmk-gI4LeUKSS9mw',
    appId: '1:538784837581:ios:65c743532284b4e19f1e84',
    messagingSenderId: '538784837581',
    projectId: 'capstone-53c84',
    databaseURL: 'https://capstone-53c84-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-53c84.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_S91nTYAWqO5gmPZbSg4lKLCj_Uv2ezc',
    appId: '1:538784837581:web:4d5b405fcd6d7cc49f1e84',
    messagingSenderId: '538784837581',
    projectId: 'capstone-53c84',
    authDomain: 'capstone-53c84.firebaseapp.com',
    databaseURL: 'https://capstone-53c84-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-53c84.appspot.com',
    measurementId: 'G-38FBSP8NWM',
  );

}